//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "artifactory")]
pub struct Model {
    #[sea_orm(primary_key)]
    #[serde(skip_deserializing)]
    pub pid: i32,
    pub name: String,
    pub ver: String,
    pub md5: String,
    pub descript: String,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tag: Option<Json>,
    pub cont_size: i64,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub min_runtime_ver: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max_runtime_ver: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub create_time: Option<DateTimeWithTimeZone>,
    pub runtime: String,
    pub s3_key: String,
    pub s3_inc_id: i32,
    pub is_artifactory_ready: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ci_info: Option<Json>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub key_extension: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::artifactory_runtime::Entity",
        from = "Column::Runtime",
        to = "super::artifactory_runtime::Column::Runtime",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ArtifactoryRuntime,
}

impl Related<super::artifactory_runtime::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ArtifactoryRuntime.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::artifactory_runtime::Entity")]
    ArtifactoryRuntime,
}
