//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "artifactory_runtime")]
pub struct Model {
    #[sea_orm(primary_key)]
    #[serde(skip_deserializing)]
    pub id: i32,
    #[sea_orm(unique)]
    pub runtime: String,
    pub ver_name: String,
    pub create_time: DateTimeWithTimeZone,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub rt_usage: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub rt_desc: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ver_int: Option<i32>,
    #[sea_orm(column_type = "JsonBinary")]
    pub file_type: Json,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::artifactory::Entity")]
    Artifactory,
}

impl Related<super::artifactory::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Artifactory.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::artifactory::Entity")]
    Artifactory,
}
