//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "doc_module_versions")]
pub struct Model {
    #[sea_orm(primary_key)]
    #[serde(skip_deserializing)]
    pub id: i32,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub create_time: Option<Date>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub change_logs: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub module_id: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub semver: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub online_date: Option<Date>,
    #[sea_orm(column_type = "Text", nullable)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub desc: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::doc_modules::Entity",
        from = "Column::ModuleId",
        to = "super::doc_modules::Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    DocModules,
}

impl Related<super::doc_modules::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DocModules.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::doc_modules::Entity")]
    DocModules,
}
