//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "doc_versions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    #[serde(skip_deserializing)]
    pub title: String,
    #[sea_orm(column_type = "Text")]
    pub short_desc: String,
    pub online_date: Date,
    #[sea_orm(column_type = "Text", nullable)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub long_desc: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub is_dev: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub change_logs: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub update_modules: Option<Vec<i32>>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {}
