//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use super::sea_orm_active_enums::Efeatureplatform;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "feature_tag_config")]
pub struct Model {
    #[sea_orm(primary_key)]
    #[serde(skip_deserializing)]
    pub id: i32,
    pub platform: Efeatureplatform,
    #[sea_orm(column_type = "JsonBinary")]
    pub feature_list: Json,
    #[sea_orm(column_type = "Text", nullable)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tag_desc: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub condition: Option<Json>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub create_avatar_name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub create_avatar_id: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub create_time: Option<DateTime>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub editer_time: Option<DateTime>,
    #[sea_orm(column_type = "Text", nullable)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub is_delete: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub state: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub new_name: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {}
