//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use super::sea_orm_active_enums::Econflicttype;
use super::sea_orm_active_enums::Efeatureplatform;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "feature_config_conflict")]
pub struct Model {
    #[sea_orm(primary_key)]
    #[serde(skip_deserializing)]
    pub id: i32,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub create_time: Option<DateTimeWithTimeZone>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub create_avatar_id: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub update_avatar_id: Option<i32>,
    pub platform: Efeatureplatform,
    pub id_base: i32,
    pub id_conflict: i32,
    pub conflict_type: Econflicttype,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,
    pub is_delete: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub update_time: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {}
