//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "feature_config_layer_rule_zh_cn")]
pub struct Model {
    #[sea_orm(primary_key)]
    #[serde(skip_deserializing)]
    pub id: i32,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub layer_name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub type_strategy_actual: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub type_strategy_expect: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub type_strategy_demotion: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub strategy_actual: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub strategy_expect: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub strategy_demotion: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub label_lv1: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub label_lv2: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub label_lv3: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub label_lv4: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub is_delete: Option<bool>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {}
