//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use super::sea_orm_active_enums::Efeatureplatform;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "feature_config")]
pub struct Model {
    #[sea_orm(primary_key)]
    #[serde(skip_deserializing)]
    pub id: i32,
    pub platform: Efeatureplatform,
    pub feature_id: i32,
    pub feature_key: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub feature_param: Json,
    #[sea_orm(column_type = "Text", nullable)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub feature_desc: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub feature_type: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub create_avatar_name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub create_avatar_id: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub create_time: Option<DateTime>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub editer_time: Option<DateTime>,
    #[sea_orm(column_type = "Text", nullable)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub solution_url: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub is_delete: Option<bool>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub strategy_actual: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub strategy_expect: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub strategy_demotion: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub labels: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub game_mode: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub layers: Option<Json>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {}
