//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

pub mod prelude;

pub mod artifactory;
pub mod artifactory_runtime;

seaography::register_entity_modules_read_only!([artifactory, artifactory_runtime,]);
