//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "mod_app")]
pub struct Model {
    #[sea_orm(primary_key)]
    #[serde(skip_deserializing)]
    pub id: i32,
    pub app_id: String,
    pub app_name: String,
    #[sea_orm(column_type = "Text", nullable)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub app_desc: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub app_web_url: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub app_icon_url: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub menu_parent_layer: Option<String>,
    pub is_delete: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {}
