//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "econflicttype")]
pub enum Econflicttype {
    #[sea_orm(string_value = "Ignored")]
    Ignored,
    #[sea_orm(string_value = "Conflict")]
    Conflict,
    #[sea_orm(string_value = "Compatible")]
    Compatible,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "efeatureplatform")]
pub enum Efeatureplatform {
    #[sea_orm(string_value = "IOS")]
    Ios,
    #[sea_orm(string_value = "GP")]
    Gp,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "esolutionstate")]
pub enum Esolutionstate {
    #[sea_orm(string_value = "SolutionCreate")]
    SolutionCreate,
    #[sea_orm(string_value = "SolutionReview")]
    SolutionReview,
    #[sea_orm(string_value = "SolutionCheck")]
    SolutionCheck,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "estwftype")]
pub enum Estwftype {
    #[sea_orm(string_value = "SOLUTION")]
    Solution,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "ewaytype")]
pub enum Ewaytype {
    #[sea_orm(string_value = "Added")]
    Added,
    #[sea_orm(string_value = "Active")]
    Active,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "labelalgotype")]
pub enum Labelalgotype {
    #[sea_orm(string_value = "Strategy")]
    Strategy,
    #[sea_orm(string_value = "Custom")]
    Custom,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "labeltype")]
pub enum Labeltype {
    #[sea_orm(string_value = "Algorithm")]
    Algorithm,
    #[sea_orm(string_value = "NonAlgorithm")]
    NonAlgorithm,
}
