//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use super::sea_orm_active_enums::Efeatureplatform;
use super::sea_orm_active_enums::Ewaytype;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "solution_draft")]
pub struct Model {
    #[sea_orm(primary_key)]
    #[serde(skip_deserializing)]
    pub id: i32,
    pub platform: Efeatureplatform,
    pub way_type: Ewaytype,
    pub way: i32,
    pub experiment_type: String,
    pub solution_type: String,
    pub other_sol_type_name: String,
    pub step: String,
    pub split_type: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub draft_info: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub layer_info: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub solution_info: Json,
    pub solution_ids: Vec<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub create_time: Option<DateTimeWithTimeZone>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub editer_time: Option<DateTimeWithTimeZone>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub create_avatar_name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub create_avatar_id: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub editer_avatar_name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub editer_avatar_id: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub is_delete: Option<bool>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {}
