//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use super::sea_orm_active_enums::Efeatureplatform;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "solution_workflow")]
pub struct Model {
    #[sea_orm(primary_key)]
    #[serde(skip_deserializing)]
    pub id: i32,
    pub platform: Efeatureplatform,
    pub desc_simple: String,
    pub list_solution_id: Json,
    pub list_layer: Json,
    pub list_result_layer: Json,
    pub cur_layer: i32,
    pub cur_layer_step: i32,
    pub state: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub create_time: Option<DateTimeWithTimeZone>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub editer_time: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {}
