//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use super::sea_orm_active_enums::Efeatureplatform;
use super::sea_orm_active_enums::Esolutionstate;
use super::sea_orm_active_enums::Ewaytype;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "solution_history")]
pub struct Model {
    #[sea_orm(primary_key)]
    #[serde(skip_deserializing)]
    pub id: i32,
    pub platform: Efeatureplatform,
    pub way_type: Ewaytype,
    pub solution_id: String,
    pub way: i32,
    pub tag: Json,
    pub solution_control_group: Json,
    pub tag_base_editer: Json,
    #[sea_orm(column_type = "Text", nullable)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub solution_desc: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub solution_desc_text: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub solution_desc_abbreviated: Option<String>,
    pub solution_state: Esolutionstate,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub create_avatar_name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub create_avatar_id: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub create_time: Option<DateTimeWithTimeZone>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub editer_time: Option<DateTimeWithTimeZone>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub is_delete: Option<bool>,
    pub solution_type: String,
    pub solution_label_id: i32,
    pub experiment_type: String,
    pub other_sol_type_name: String,
    #[sea_orm(column_type = "Text", nullable)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
    pub action: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub url_data_analysis_report: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub url_doc: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub url_cloud_effect: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::solution_label::Entity",
        from = "Column::SolutionLabelId",
        to = "super::solution_label::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    SolutionLabel,
}

impl Related<super::solution_label::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SolutionLabel.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::solution_label::Entity")]
    SolutionLabel,
}
