//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "solution_label")]
pub struct Model {
    #[sea_orm(primary_key)]
    #[serde(skip_deserializing)]
    pub id: i32,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub create_time: Option<DateTimeWithTimeZone>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub create_avatar_id: Option<i32>,
    pub label: String,
    pub is_base: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub is_delete: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub prefix: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub update_time: Option<DateTimeWithTimeZone>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::solution::Entity")]
    Solution,
    #[sea_orm(has_many = "super::solution_history::Entity")]
    SolutionHistory,
}

impl Related<super::solution::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Solution.def()
    }
}

impl Related<super::solution_history::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SolutionHistory.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::solution::Entity")]
    Solution,
    #[sea_orm(entity = "super::solution_history::Entity")]
    SolutionHistory,
}
