//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "st_polling_log")]
pub struct Model {
    #[sea_orm(primary_key)]
    #[serde(skip_deserializing)]
    pub id: i64,
    pub task_id: i64,
    pub retry_count: i64,
    pub protocol_type: i32,
    pub endpoint: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub http_method: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub headers: Option<Json>,
    #[sea_orm(column_type = "Text", nullable)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub request_body: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub response_status: Option<i64>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub response_headers: Option<Json>,
    #[sea_orm(column_type = "Text", nullable)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub response_body: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub response_time: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error_message: Option<String>,
    pub executed_at: DateTimeWithTimeZone,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub created_at: Option<DateTimeWithTimeZone>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<DateTimeWithTimeZone>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub deleted_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {}
