//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use super::sea_orm_active_enums::Efeatureplatform;
use super::sea_orm_active_enums::Ewaytype;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "st_wf_solution_item")]
pub struct Model {
    #[sea_orm(primary_key)]
    #[serde(skip_deserializing)]
    pub id: i32,
    pub solution_id: i32,
    pub platform: Efeatureplatform,
    pub way: i32,
    pub way_type: Ewaytype,
    pub solution_type: String,
    pub experiment_type: String,
    pub list_solution_id: Json,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub base_solution_id: Option<Json>,
    pub other_sol_type_name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::st_wf_solution::Entity",
        from = "Column::SolutionId",
        to = "super::st_wf_solution::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    StWfSolution,
}

impl Related<super::st_wf_solution::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StWfSolution.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::st_wf_solution::Entity")]
    StWfSolution,
}
