//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use super::sea_orm_active_enums::Estwftype;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "st_workflow")]
pub struct Model {
    #[sea_orm(primary_key)]
    #[serde(skip_deserializing)]
    pub id: i32,
    pub id_wf_data: i32,
    pub st_wf_type: Estwftype,
    pub list_layer: Json,
    pub list_result_layer: Json,
    pub list_idx: Json,
    pub state: String,
    pub notif: Json,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub create_time: Option<DateTimeWithTimeZone>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub editer_time: Option<DateTimeWithTimeZone>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub lock: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub is_delete: Option<bool>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {}
