//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "st_wf_sol_pack")]
pub struct Model {
    #[sea_orm(primary_key)]
    #[serde(skip_deserializing)]
    pub id: i32,
    pub id_wf_solution: i32,
    pub project: String,
    #[sea_orm(unique)]
    pub name_pack: String,
    pub pack_data: Json,
    pub pack_result: Json,
    pub deploy_info: Json,
    pub state: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub start_time: Option<DateTimeWithTimeZone>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub end_time: Option<DateTimeWithTimeZone>,
    pub is_delete: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {}
