//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use super::sea_orm_active_enums::Efeatureplatform;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "st_yunxiao_blackbox_test_events_history")]
pub struct Model {
    #[sea_orm(primary_key)]
    #[serde(skip_deserializing)]
    pub id: i64,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub created_at: Option<DateTimeWithTimeZone>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<DateTimeWithTimeZone>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub wf_solution_id: i64,
    pub solution_id: i64,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub platform: Option<Efeatureplatform>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub solution_id_str: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tester: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub is_h5_baseboard_single_feature_test: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub is_h5_feature_conflict_test: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub is_h5_legacy_data_compatible: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub is_h5_anti_penetration_small_bundle: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub is_real_device_perf_and_compatible: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub is_real_device_main_flow_test: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub is_real_device_ad_test: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub remark: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub event_status: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cancel_reason: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub failure_reason: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub is_solution_deleted: Option<bool>,
    pub operation_type: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub changed_field_name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub new_value: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub old_value: Option<String>,
    pub operator_id: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub operator_name: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {}
