//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use super::sea_orm_active_enums::Efeatureplatform;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "st_yunxiao_task_events_history")]
pub struct Model {
    #[sea_orm(primary_key)]
    #[serde(skip_deserializing)]
    pub id: i64,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub created_at: Option<DateTimeWithTimeZone>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<DateTimeWithTimeZone>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub yunxiao_event_id: i64,
    pub wf_solution_id: i64,
    pub solution_id: i64,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub platform: Option<Efeatureplatform>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub solution_id_str: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub priority: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub responsible_person: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub developer: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tester: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub dev_value_point: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub test_value_point: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub solution_create_avatar_id: Option<i64>,
    pub operation_type: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub changed_field_name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub new_value: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub old_value: Option<String>,
    pub operator_id: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub operator_name: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {}
